package org.darod.elearning.gateway.dao;

import org.darod.elearning.gateway.dataobject.ChapterDO;
import org.springframework.stereotype.Repository;

@Repository
public interface ChapterDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_info
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_info
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int insert(ChapterDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_info
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int insertSelective(ChapterDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_info
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    ChapterDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_info
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int updateByPrimaryKeySelective(ChapterDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter_info
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int updateByPrimaryKey(ChapterDO record);
}