package org.darod.elearning.gateway.dao;

import org.apache.ibatis.annotations.Param;
import org.darod.elearning.gateway.dataobject.CommentDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CommentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Tue Jul 16 13:03:16 CST 2019
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Tue Jul 16 13:03:16 CST 2019
     */
    int insert(CommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Tue Jul 16 13:03:16 CST 2019
     */
    int insertSelective(CommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Tue Jul 16 13:03:16 CST 2019
     */
    CommentDO selectByPrimaryKey(Integer commentId);

    List<CommentDO> selectChapterCommentByCourseIdAndChapterId(@Param("courseId") Integer courseId, @Param("chapterId") Integer chapterId);

    List<CommentDO> selectCourseCommentByCourseId(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Tue Jul 16 13:03:16 CST 2019
     */
    int updateByPrimaryKeySelective(CommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Tue Jul 16 13:03:16 CST 2019
     */
    int updateByPrimaryKey(CommentDO record);
}