package org.darod.elearning.gateway.dao;

import org.darod.elearning.common.dto.CoursePageModel;
import org.darod.elearning.gateway.dataobject.CourseDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CourseDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Mon Jul 01 19:15:19 CST 2019
     */
    int deleteByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Mon Jul 01 19:15:19 CST 2019
     */
    int insert(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Mon Jul 01 19:15:19 CST 2019
     */
    int insertSelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Mon Jul 01 19:15:19 CST 2019
     */
    CourseDO selectByPrimaryKey(Integer courseId);

    CourseDO selectByPrimaryKeyForUpdate(Integer courseId);

    List<CourseDO> getAllCourseInfo();

    List<CourseDO> getAllFreeCourseInfo();

    List<CourseDO> getCourseInfoLimited(CoursePageModel coursePageModel);

    List<CourseDO> getCourseByTeacherId(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Mon Jul 01 19:15:19 CST 2019
     */
    int updateByPrimaryKeySelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated Mon Jul 01 19:15:19 CST 2019
     */
    int updateByPrimaryKey(CourseDO record);
}