package org.darod.elearning.gateway.dao;

import org.apache.ibatis.annotations.Param;
import org.darod.elearning.gateway.dataobject.ForbidDO;
import org.darod.elearning.gateway.dataobject.UserRoleDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ForbidDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forbid
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    int deleteByPrimaryKey(Integer forbidId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forbid
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    int insert(ForbidDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forbid
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    int insertSelective(ForbidDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forbid
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    ForbidDO selectByPrimaryKey(Integer forbidId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forbid
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    int updateByPrimaryKeySelective(ForbidDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forbid
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    int updateByPrimaryKey(ForbidDO record);


    List<String> getPrivilegeWithForbid(@Param("userId") Integer userId,@Param("list") List<UserRoleDO> list);
}