package org.darod.elearning.gateway.dao;

import org.darod.elearning.gateway.dataobject.LiveRoomDO;

public interface LiveRoomDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_room
     *
     * @mbg.generated Tue Jul 16 13:03:16 CST 2019
     */
    int deleteByPrimaryKey(Integer roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_room
     *
     * @mbg.generated Tue Jul 16 13:03:16 CST 2019
     */
    int insert(LiveRoomDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_room
     *
     * @mbg.generated Tue Jul 16 13:03:16 CST 2019
     */
    int insertSelective(LiveRoomDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_room
     *
     * @mbg.generated Tue Jul 16 13:03:16 CST 2019
     */
    LiveRoomDO selectByPrimaryKey(Integer roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_room
     *
     * @mbg.generated Tue Jul 16 13:03:16 CST 2019
     */
    int updateByPrimaryKeySelective(LiveRoomDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live_room
     *
     * @mbg.generated Tue Jul 16 13:03:16 CST 2019
     */
    int updateByPrimaryKey(LiveRoomDO record);
}