package org.darod.elearning.gateway.dao;

import org.apache.ibatis.annotations.Param;
import org.darod.elearning.gateway.dataobject.OrderDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Jul 15 12:54:50 CST 2019
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Jul 15 12:54:50 CST 2019
     */
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Jul 15 12:54:50 CST 2019
     */
    int insertSelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Jul 15 12:54:50 CST 2019
     */
    OrderDO selectByPrimaryKey(String orderId);

    OrderDO selectByPrimaryKeyForUpdate(String orderId);

    List<OrderDO> selectByUserIdAndCourseId(@Param("userId") Integer userId, @Param("courseId") Integer courseId);

    List<OrderDO> selectByUserIdAndCourseIdForUpdate(@Param("userId") Integer userId, @Param("courseId") Integer courseId);

    List<OrderDO> getAllOrderInfo();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Jul 15 12:54:50 CST 2019
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Mon Jul 15 12:54:50 CST 2019
     */
    int updateByPrimaryKey(OrderDO record);
}