package org.darod.elearning.gateway.dao;

import org.darod.elearning.gateway.dataobject.RolePrivilegeDO;
import org.darod.elearning.gateway.dataobject.UserRoleDO;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface RolePrivilegeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    int deleteByPrimaryKey(Integer rolePrivilegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    int insert(RolePrivilegeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    int insertSelective(RolePrivilegeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    RolePrivilegeDO selectByPrimaryKey(Integer rolePrivilegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    int updateByPrimaryKeySelective(RolePrivilegeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    int updateByPrimaryKey(RolePrivilegeDO record);

    List<RolePrivilegeDO> getRolePrivilegeByRoleList(List<UserRoleDO> roleList);
}