package org.darod.elearning.gateway.dao;

import org.darod.elearning.gateway.dataobject.UserLearnDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserLearnDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int insert(UserLearnDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int insertSelective(UserLearnDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    UserLearnDO selectByPrimaryKey(Integer id);

    List<UserLearnDO> selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int updateByPrimaryKeySelective(UserLearnDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int updateByPrimaryKey(UserLearnDO record);
}