package org.darod.elearning.gateway.dao;

import org.darod.elearning.gateway.dataobject.UserRoleDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository

public interface UserRoleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    int deleteByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    int insert(UserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    int insertSelective(UserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    UserRoleDO selectByPrimaryKey(Integer userRoleId);

    List<UserRoleDO> getUserRoleInfoByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    int updateByPrimaryKeySelective(UserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    int updateByPrimaryKey(UserRoleDO record);
}