package org.darod.elearning.gateway.dao;

import org.darod.elearning.gateway.dataobject.UserPublisherDO;
import org.springframework.stereotype.Repository;

@Repository
public interface UserPublisherDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_publisher
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_publisher
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int insert(UserPublisherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_publisher
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int insertSelective(UserPublisherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_publisher
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    UserPublisherDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_publisher
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int updateByPrimaryKeySelective(UserPublisherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_publisher
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int updateByPrimaryKey(UserPublisherDO record);
}