package org.darod.elearning.gateway.dao;

import org.apache.ibatis.annotations.Param;
import org.darod.elearning.common.dto.CoursePageModel;
import org.darod.elearning.gateway.dataobject.UserLearnDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserLearnDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int deleteByPrimaryKey(Integer learnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int insert(UserLearnDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int insertSelective(UserLearnDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    UserLearnDO selectByPrimaryKey(Integer learnId);

    UserLearnDO selectByUserIdAndCourseId(@Param("userId") Integer userId, @Param("courseId") Integer courseId);

    List<UserLearnDO> selectByUserId(Integer userId);

    UserLearnDO selectUserLearnAllByLearnId(Integer learnId);

    List<UserLearnDO> selectUserLearnAllByUserId(Integer userId);

    List<UserLearnDO> selectUserLearnAllByUserIdLimited(CoursePageModel coursePageModel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int updateByPrimaryKeySelective(UserLearnDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_learn
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    int updateByPrimaryKey(UserLearnDO record);
}