package org.darod.elearning.gateway.dataobject;

import java.util.Date;

public class ChapterDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_info.id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_info.chapter_no
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Byte chapterNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_info.chapter_name
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private String chapterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_info.chapter_description
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private String chapterDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_info.video_url
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_info.publish_time
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_info.total_time
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private String totalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_info.chapter_state
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Byte chapterState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter_info.course_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Integer courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_info.id
     *
     * @return the value of chapter_info.id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_info.id
     *
     * @param id the value for chapter_info.id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_info.chapter_no
     *
     * @return the value of chapter_info.chapter_no
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Byte getChapterNo() {
        return chapterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_info.chapter_no
     *
     * @param chapterNo the value for chapter_info.chapter_no
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setChapterNo(Byte chapterNo) {
        this.chapterNo = chapterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_info.chapter_name
     *
     * @return the value of chapter_info.chapter_name
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_info.chapter_name
     *
     * @param chapterName the value for chapter_info.chapter_name
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_info.chapter_description
     *
     * @return the value of chapter_info.chapter_description
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getChapterDescription() {
        return chapterDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_info.chapter_description
     *
     * @param chapterDescription the value for chapter_info.chapter_description
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setChapterDescription(String chapterDescription) {
        this.chapterDescription = chapterDescription == null ? null : chapterDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_info.video_url
     *
     * @return the value of chapter_info.video_url
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_info.video_url
     *
     * @param videoUrl the value for chapter_info.video_url
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_info.publish_time
     *
     * @return the value of chapter_info.publish_time
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_info.publish_time
     *
     * @param publishTime the value for chapter_info.publish_time
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_info.total_time
     *
     * @return the value of chapter_info.total_time
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getTotalTime() {
        return totalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_info.total_time
     *
     * @param totalTime the value for chapter_info.total_time
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setTotalTime(String totalTime) {
        this.totalTime = totalTime == null ? null : totalTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_info.chapter_state
     *
     * @return the value of chapter_info.chapter_state
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Byte getChapterState() {
        return chapterState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_info.chapter_state
     *
     * @param chapterState the value for chapter_info.chapter_state
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setChapterState(Byte chapterState) {
        this.chapterState = chapterState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter_info.course_id
     *
     * @return the value of chapter_info.course_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter_info.course_id
     *
     * @param courseId the value for chapter_info.course_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
}