package org.darod.elearning.gateway.dataobject;

import java.util.Date;

public class ForbidDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forbid.forbid_id
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    private Integer forbidId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forbid.user_id
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forbid.role_name
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forbid.privilege_name
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    private String privilegeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forbid.forbid_time
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    private Date forbidTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forbid.finish_time
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forbid.forbid_reason
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    private String forbidReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forbid.forbid_id
     *
     * @return the value of forbid.forbid_id
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    public Integer getForbidId() {
        return forbidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forbid.forbid_id
     *
     * @param forbidId the value for forbid.forbid_id
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    public void setForbidId(Integer forbidId) {
        this.forbidId = forbidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forbid.user_id
     *
     * @return the value of forbid.user_id
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forbid.user_id
     *
     * @param userId the value for forbid.user_id
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forbid.role_name
     *
     * @return the value of forbid.role_name
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forbid.role_name
     *
     * @param roleName the value for forbid.role_name
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forbid.privilege_name
     *
     * @return the value of forbid.privilege_name
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    public String getPriviliegeName() {
        return privilegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forbid.privilege_name
     *
     * @param privilegeName the value for forbid.privilege_name
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    public void setPriviliegeName(String privilegeName) {
        this.privilegeName = privilegeName == null ? null : privilegeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forbid.forbid_time
     *
     * @return the value of forbid.forbid_time
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    public Date getForbidTime() {
        return forbidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forbid.forbid_time
     *
     * @param forbidTime the value for forbid.forbid_time
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    public void setForbidTime(Date forbidTime) {
        this.forbidTime = forbidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forbid.finish_time
     *
     * @return the value of forbid.finish_time
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forbid.finish_time
     *
     * @param finishTime the value for forbid.finish_time
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forbid.forbid_reason
     *
     * @return the value of forbid.forbid_reason
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    public String getForbidReason() {
        return forbidReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forbid.forbid_reason
     *
     * @param forbidReason the value for forbid.forbid_reason
     *
     * @mbg.generated Sat Jul 20 17:34:56 CST 2019
     */
    public void setForbidReason(String forbidReason) {
        this.forbidReason = forbidReason == null ? null : forbidReason.trim();
    }
}