package org.darod.elearning.gateway.dataobject;

public class RolePrivilegeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_privilege.role_privilege_id
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    private Integer rolePrivilegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_privilege.role_name
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_privilege.privilege_name
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    private String privilegeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_privilege.role_privilege_id
     *
     * @return the value of role_privilege.role_privilege_id
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    public Integer getRolePrivilegeId() {
        return rolePrivilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_privilege.role_privilege_id
     *
     * @param rolePrivilegeId the value for role_privilege.role_privilege_id
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    public void setRolePrivilegeId(Integer rolePrivilegeId) {
        this.rolePrivilegeId = rolePrivilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_privilege.role_name
     *
     * @return the value of role_privilege.role_name
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_privilege.role_name
     *
     * @param roleName the value for role_privilege.role_name
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_privilege.privilege_name
     *
     * @return the value of role_privilege.privilege_name
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    public String getPrivilegeName() {
        return privilegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_privilege.privilege_name
     *
     * @param privilegeName the value for role_privilege.privilege_name
     *
     * @mbg.generated Sat Jul 20 17:53:56 CST 2019
     */
    public void setPrivilegeName(String privilegeName) {
        this.privilegeName = privilegeName == null ? null : privilegeName.trim();
    }
}