package org.darod.elearning.gateway.dataobject;

import java.util.Date;

public class UserLearnDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_learn.id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Integer learnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_learn.user_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_learn.course_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_learn.learn_time
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Date learnTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_learn.last_chapter
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Integer lastChapter;

    private CourseDO courseDO;

    private ChapterDO chapterDO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_learn.id
     *
     * @return the value of user_learn.id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getLearnId() {
        return learnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_learn.id
     *
     * @param learnId the value for user_learn.id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setLearnId(Integer learnId) {
        this.learnId = learnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_learn.user_id
     *
     * @return the value of user_learn.user_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_learn.user_id
     *
     * @param userId the value for user_learn.user_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_learn.course_id
     *
     * @return the value of user_learn.course_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_learn.course_id
     *
     * @param courseId the value for user_learn.course_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_learn.learn_time
     *
     * @return the value of user_learn.learn_time
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Date getLearnTime() {
        return learnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_learn.learn_time
     *
     * @param learnTime the value for user_learn.learn_time
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setLearnTime(Date learnTime) {
        this.learnTime = learnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_learn.last_chapter
     *
     * @return the value of user_learn.last_chapter
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getLastChapter() {
        return lastChapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_learn.last_chapter
     *
     * @param lastChapter the value for user_learn.last_chapter
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setLastChapter(Integer lastChapter) {
        this.lastChapter = lastChapter;
    }

    public CourseDO getCourseDO() {
        return courseDO;
    }

    public void setCourseDO(CourseDO courseDO) {
        this.courseDO = courseDO;
    }

    public ChapterDO getChapterDO() {
        return chapterDO;
    }

    public void setChapterDO(ChapterDO chapterDO) {
        this.chapterDO = chapterDO;
    }
}