package org.darod.elearning.gateway.dataobject;

public class UserPublisherDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_publisher.id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_publisher.user_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_publisher.id_card
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_publisher.cost_percent
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Integer costPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_publisher.publisher_state
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Integer publisherState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_publisher.id
     *
     * @return the value of user_publisher.id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_publisher.id
     *
     * @param id the value for user_publisher.id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_publisher.user_id
     *
     * @return the value of user_publisher.user_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_publisher.user_id
     *
     * @param userId the value for user_publisher.user_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_publisher.id_card
     *
     * @return the value of user_publisher.id_card
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_publisher.id_card
     *
     * @param idCard the value for user_publisher.id_card
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_publisher.cost_percent
     *
     * @return the value of user_publisher.cost_percent
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getCostPercent() {
        return costPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_publisher.cost_percent
     *
     * @param costPercent the value for user_publisher.cost_percent
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setCostPercent(Integer costPercent) {
        this.costPercent = costPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_publisher.publisher_state
     *
     * @return the value of user_publisher.publisher_state
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getPublisherState() {
        return publisherState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_publisher.publisher_state
     *
     * @param publisherState the value for user_publisher.publisher_state
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setPublisherState(Integer publisherState) {
        this.publisherState = publisherState;
    }
}