package org.darod.elearning.gateway.dataobject;

import java.util.Date;

public class UserLearnDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_learn.id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_learn.user_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_learn.course_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_learn.learn_time
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Date learnTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_learn.last_chapter
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Byte lastChapter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_learn.id
     *
     * @return the value of user_learn.id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_learn.id
     *
     * @param id the value for user_learn.id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_learn.user_id
     *
     * @return the value of user_learn.user_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_learn.user_id
     *
     * @param userId the value for user_learn.user_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_learn.course_id
     *
     * @return the value of user_learn.course_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_learn.course_id
     *
     * @param courseId the value for user_learn.course_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_learn.learn_time
     *
     * @return the value of user_learn.learn_time
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Date getLearnTime() {
        return learnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_learn.learn_time
     *
     * @param learnTime the value for user_learn.learn_time
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setLearnTime(Date learnTime) {
        this.learnTime = learnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_learn.last_chapter
     *
     * @return the value of user_learn.last_chapter
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Byte getLastChapter() {
        return lastChapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_learn.last_chapter
     *
     * @param lastChapter the value for user_learn.last_chapter
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setLastChapter(Byte lastChapter) {
        this.lastChapter = lastChapter;
    }
}