package org.darod.elearning.gateway.dataobject;

import org.hibernate.validator.constraints.URL;

import javax.validation.constraints.*;
import java.io.Serializable;

public class UserDO implements Serializable {
    private Integer userId;
    @NotBlank(message = "用户名不能为空")
    private String name;
    @NotNull(message = "性别不能为空")
    private Integer gender;
    @NotNull(message = "年龄不能为空")
    @Min(value = 0, message = "年龄必须大于0岁")
    @Max(value = 150, message = "年龄不能大于150岁")
    private Integer age;
    private String telphone;
    private String registerMode;
    private String thirdPartyId;
    @Email(message = "邮箱格式不正确")
    private String email;
    @NotNull(message = "头像URL不能为空")
    @URL(message = "URL格式不正确")
    private String headUrl;
    private Integer userState;
    private String userDescribtion;













    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     * @mbg.generated Mon Jul 01 19:05:27 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.age
     *
     * @return the value of user.age
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.age
     *
     * @param age the value for user.age
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.telphone
     *
     * @return the value of user.telphone
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.telphone
     *
     * @param telphone the value for user.telphone
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.register_mode
     *
     * @return the value of user.register_mode
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getRegisterMode() {
        return registerMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.register_mode
     *
     * @param registerMode the value for user.register_mode
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setRegisterMode(String registerMode) {
        this.registerMode = registerMode == null ? null : registerMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.third_party_id
     *
     * @return the value of user.third_party_id
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getThirdPartyId() {
        return thirdPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.third_party_id
     *
     * @param thirdPartyId the value for user.third_party_id
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setThirdPartyId(String thirdPartyId) {
        this.thirdPartyId = thirdPartyId == null ? null : thirdPartyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.head_url
     *
     * @return the value of user.head_url
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.head_url
     *
     * @param headUrl the value for user.head_url
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_state
     *
     * @return the value of user.user_state
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_state
     *
     * @param userState the value for user.user_state
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setUserState(Integer userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_describtion
     *
     * @return the value of user.user_describtion
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getUserDescribtion() {
        return userDescribtion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_describtion
     *
     * @param userDescribtion the value for user.user_describtion
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setUserDescribtion(String userDescribtion) {
        this.userDescribtion = userDescribtion == null ? null : userDescribtion.trim();
    }
}