package org.darod.elearning.gateway.dataobject;

public class UserRoleDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.user_role_id
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    private Integer userRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.user_id
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.role_name
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.user_role_id
     *
     * @return the value of user_role.user_role_id
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    public Integer getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.user_role_id
     *
     * @param userRoleId the value for user_role.user_role_id
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.user_id
     *
     * @return the value of user_role.user_id
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.user_id
     *
     * @param userId the value for user_role.user_id
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.role_name
     *
     * @return the value of user_role.role_name
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.role_name
     *
     * @param roleName the value for user_role.role_name
     *
     * @mbg.generated Sat Jul 20 17:29:29 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}