package org.darod.elearning.gateway.dataobject;

import java.io.Serializable;

public class UserDO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.age
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.telphone
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.register_mode
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private String registerMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.third_party_id
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private String thirdPartyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.head_url
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private String headUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_state
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private Byte userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_describtion
     *
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    private String userDescribtion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     * @mbg.generated Mon Jul 01 19:05:27 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     * @mbg.generated Mon Jul 01 19:05:27 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.age
     *
     * @return the value of user.age
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.age
     *
     * @param age the value for user.age
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.telphone
     *
     * @return the value of user.telphone
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.telphone
     *
     * @param telphone the value for user.telphone
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.register_mode
     *
     * @return the value of user.register_mode
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getRegisterMode() {
        return registerMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.register_mode
     *
     * @param registerMode the value for user.register_mode
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setRegisterMode(String registerMode) {
        this.registerMode = registerMode == null ? null : registerMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.third_party_id
     *
     * @return the value of user.third_party_id
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getThirdPartyId() {
        return thirdPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.third_party_id
     *
     * @param thirdPartyId the value for user.third_party_id
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setThirdPartyId(String thirdPartyId) {
        this.thirdPartyId = thirdPartyId == null ? null : thirdPartyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.head_url
     *
     * @return the value of user.head_url
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.head_url
     *
     * @param headUrl the value for user.head_url
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_state
     *
     * @return the value of user.user_state
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public Byte getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_state
     *
     * @param userState the value for user.user_state
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setUserState(Byte userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_describtion
     *
     * @return the value of user.user_describtion
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public String getUserDescribtion() {
        return userDescribtion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_describtion
     *
     * @param userDescribtion the value for user.user_describtion
     * @mbg.generated Mon Jun 24 18:28:14 CST 2019
     */
    public void setUserDescribtion(String userDescribtion) {
        this.userDescribtion = userDescribtion == null ? null : userDescribtion.trim();
    }
}